### ISSUE TITLE
Flatpak version fails to build with the KDE 6.6 Flatpak Runtime 

### ISSUE THREAD

**Issue by alastortenebris** [YACReader/yacreader#431]
The buildlog [here](https://buildbot.flathub.org/#/builders/6/builds/105276) shows the following error:

```
FAILED: src/gn/desc_builder.o 
g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
../src/gn/desc_builder.cc: In member function ‘base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)’:
../src/gn/desc_builder.cc:180:21: error: redundant move in return statement [-Werror=redundant-move]
  180 |     return std::move(res);
      |            ~~~~~~~~~^~~~~
../src/gn/desc_builder.cc:180:21: note: remove ‘std::move’ call
../src/gn/desc_builder.cc: In instantiation of ‘base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const std::vector<T>&) [with T = Value]’:
../src/gn/desc_builder.cc:194:27:   required from here
../src/gn/desc_builder.cc:171:25: error: redundant move in return statement [-Werror=redundant-move]
  171 |     return std::move(res);
      |                         ^
../src/gn/desc_builder.cc:171:25: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
```
The 6.6 runtime adds KImageFormats for QT6 support, allowing YACReader to open stuff like `.jxl` files, so being able to use that runtime would be ideal.

**Comment by selmf** [comment]
Sorry for not getting back to you earlier. I actually saw your effort and already had a look at the problem.

The issue seems to be a regression in the GN build tool that breaks the build with GCC 12. The gn upstream already fixed this so my hope is that you just need to point the build to the current head of the gn git repo:

https://gn.googlesource.com/gn/

If that does not help I'll have another look.
